source:
  enabled: false
  name_template: "{{ .ProjectName }}-{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test -v -cover ./...

builds:
  - binary: "poorman"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    

dockers:
  - image_templates:
      - "hibare/poorman:{{ .Version }}-amd64"
      - "hibare/poorman:latest-amd64"
      - "ghcr.io/hibare/poorman:{{ .Version }}-amd64"
      - "ghcr.io/hibare/poorman:latest-amd64"
    use: buildx
    goarch: amd64
    goos: linux
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "hibare/poorman:{{ .Version }}-arm64"
      - "hibare/poorman:latest-arm64"
      - "ghcr.io/hibare/poorman:{{ .Version }}-arm64"
      - "ghcr.io/hibare/poorman:latest-arm64"
    use: buildx
    goarch: arm64
    goos: linux
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

  - image_templates:
      - "hibare/poorman:{{ .Version }}-armv6"
      - "hibare/poorman:latest-armv6"
      - "ghcr.io/hibare/poorman:{{ .Version }}-armv6"
      - "ghcr.io/hibare/poorman:latest-armv6"
    use: buildx
    goarch: arm
    goos: linux
    goarm: "6"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"

  - image_templates:
      - "hibare/poorman:{{ .Version }}-armv7"
      - "hibare/poorman:latest-armv7"
      - "ghcr.io/hibare/poorman:{{ .Version }}-armv7"
      - "ghcr.io/hibare/poorman:latest-armv7"
    use: buildx
    goarch: arm
    goos: linux
    goarm: "7"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: 'hibare/poorman:{{ .Version }}'
    image_templates:
      - 'hibare/poorman:{{ .Version }}-amd64'
      - 'hibare/poorman:{{ .Version }}-arm64'
      - 'hibare/poorman:{{ .Version }}-armv6'
      - 'hibare/poorman:{{ .Version }}-armv7'

  - name_template: 'ghcr.io/hibare/poorman:{{ .Version }}'
    image_templates:
      - 'ghcr.io/hibare/poorman:{{ .Version }}-amd64'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-arm64'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-armv6'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-armv7'

  - name_template: 'hibare/poorman:latest'
    image_templates:
      - 'hibare/poorman:{{ .Version }}-amd64'
      - 'hibare/poorman:{{ .Version }}-arm64'
      - 'hibare/poorman:{{ .Version }}-armv6'
      - 'hibare/poorman:{{ .Version }}-armv7'

  - name_template: 'ghcr.io/hibare/poorman:latest'
    image_templates:
      - 'ghcr.io/hibare/poorman:{{ .Version }}-amd64'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-arm64'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-armv6'
      - 'ghcr.io/hibare/poorman:{{ .Version }}-armv7'
      
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: 
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

docker_signs:
- cmd: cosign
  artifacts: manifests
  output: true
  args:
  - 'sign'
  - '${artifact}'
  - '--yes'
    
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
