source:
  enabled: false
  name_template: "{{ .ProjectName }}-{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test -v -cover ./...

builds:
  - binary: "poorman"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    
dockers:
  - image_templates:
      - "hibare/poorman:latest"
      - "hibare/poorman:{{ .Version }}"
      - "hibare/poorman:{{ .Major }}"
      - "hibare/poorman:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/hibare/poorman:latest"
      - "ghcr.io/hibare/poorman:{{ .Version }}"
      - "ghcr.io/hibare/poorman:{{ .Major }}"
      - "ghcr.io/hibare/poorman:{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: 
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

docker_signs:
- cmd: cosign
  artifacts: manifests
  output: true
  args:
  - 'sign'
  - '${artifact}'
  - '--yes'
    
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
