name: Dummy

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the workflow on

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          echo "Dummy action ran"
