name: Create PR on Friday Midnight IST

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5' # Runs every Friday midnight IST

jobs:
  create-pr:
    permissions:
      contents: write
      pull-requests: write
    uses: hibare/.github/.github/workflows/pr-creator.yml@f2ff32dea70db639092f5927623f59ed83099cec # main
    with:
      base_branch: main
      head_branch: dev
