name: "Release published"
on:
  release:
    types: [published, edited]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get release version
        run: echo "Release version=$GITHUB_REF"

      - name: Trigger hooks
        run: |
          echo ${{ github.event.release }}
