name: "Release published"
on:
  release:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Trigger hooks
        run: |
          LATEST_VERSION=$(gh release list | grep Latest | cut -f 3 | sed 's/^v//')
          CURRENT_VERSION=$(npm pkg get version | tr -d '"')

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            npm pkg set 'version'="$LATEST_VERSION"
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add package.json 
            git commit -m "[Auto] Update version to $LATEST_VERSION"
            git push origin main
            echo "Update version to $LATEST_VERSION"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
