name: Test - Release

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
  push:
    tags:
      - "*"
jobs:
  release:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))}}
    
    uses: hibare/.github/workflows/docker-image-build-publish.yml
    with:
      image_names: hibare/poormanrepo ghcr.io/hibare/poormanrepo
      tags: test latest
      build_args: VERSION=test FOO=bar
      platforms: linux/amd64
    secrets: inherit

