name: Test shared wf

on:
    workflow_dispatch:


jobs:
    test-shared-wf:
        name: test shared wf
        runs-on: ubuntu-latest
        steps:
            - uses: hibare/.github/test-shared-wf@test-shared-wf