name: Test - Release

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
  push:
    tags:
      - "v*"
    branches:
      - "dev"

jobs:
  build-input:
    runs-on: ubuntu-latest
    outputs:
      docker_tags: ${{ steps.set-docker-tags.outputs.docker_tags }}
      docker_image_names: ${{ steps.set-docker-image-names.outputs.docker_image_names }}

    steps:
      - name: Set Docker Tags
        id: set-docker-tags
        run: |
          DOCKER_TAGS=""
          
          if [ "${{ github.event_name }}" == "push" ]; then
            if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
              DOCKER_TAGS="dev"
            elif [[ "${{ github.ref }}" == "refs/tags/v"* ]]; then
              DOCKER_TAGS="type=semver,pattern={{version}} type=semver,pattern={{major}}"
            fi
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            DOCKER_TAGS="test"
          else
            echo "Unknown event: ${{ github.event_name }}"
            exit 1
          fi

          echo "docker_tags=$DOCKER_TAGS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Docker Image Names
        id: set-docker-image-names
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            IMAGE_NAMES="hibare/poormansrepo"
          else
            IMAGE_NAMES="hibare/poormansrepo ghcr.io/hibare/poormansrepo"
          fi
          
          echo "docker_image_names=$IMAGE_NAMES" >> $GITHUB_OUTPUT
        shell: bash
  
  docker-image-build-publish:
    permissions:
      contents: write
      id-token: write # For cosign
      packages: write # For GHCR
    needs: build-input
    uses: hibare/.github/.github/workflows/docker-image-build-publish.yml@main
    with:
      image_names: ${{ needs.build-input.outputs.docker_image_names }}
      tags: ${{ needs.build-input.outputs.docker_tags }}
      platforms: linux/amd64
      push_dockerhub: ${{ github.event_name != 'pull_request' }}
      push_ghcr: ${{ github.event_name != 'pull_request' }}
    secrets: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      