name: Test / Release

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
  push:
    tags:
      - "*"
jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Cosign install
        uses: sigstore/cosign-installer@main

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: ${{ if github.event_name == 'pull_request' }} release --skip=sign,publish --snapshot --clean ${{ else }} release --clean ${{ endif }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
